import { z } from 'zod';

export const DepartmentSchema = z.object({
  ID: z.string().nullish(),
  Id: z.string().nullish(),
  id: z.string().nullish(),
  Name: z.string().nullish(),
  name: z.string().nullish(),
  Language: z.string().nullish(),
  language: z.string().nullish(),
}).transform(val => ({
  id: val.id || val.Id || val.ID || '',
  name: val.name || val.Name || '',
  language: val.language || val.Language || undefined,
}));

export const ClientSchema = z.object({
  ID: z.string().nullish(),
  Id: z.string().nullish(),
  id: z.string().nullish(),
  AccountNumberID: z.string().nullish(),
  account_number_id: z.string().nullish(),
  Name: z.string().nullish(),
  name: z.string().nullish(),
  PrimaryPhoneNumber: z.string().nullish(),
  primary_phone_number: z.string().nullish(),
  IsNewClient: z.boolean().nullish(),
  is_new_client: z.boolean().nullish(),
  IsOptin: z.boolean().nullish(),
  is_opt_in: z.boolean().nullish(),
  IsOrg: z.boolean().nullish(),
  is_org: z.boolean().nullish(),
  IsPhoneSelected: z.boolean().nullish(),
  is_phone_selected: z.boolean().nullish(),
  IsLocked: z.boolean().nullish(),
  is_locked: z.boolean().nullish(),
  IsGuestAccount: z.boolean().nullish(),
  is_guest_account: z.boolean().nullish(),
}).transform(val => ({
  id: val.id || val.Id || val.ID || '',
  account_number_id: val.account_number_id || val.AccountNumberID || undefined,
  name: val.name || val.Name || undefined,
  primary_phone_number: val.primary_phone_number || val.PrimaryPhoneNumber || undefined,
  is_new_client: val.is_new_client ?? val.IsNewClient ?? false,
  is_opt_in: val.is_opt_in ?? val.IsOptin ?? false,
  is_org: val.is_org ?? val.IsOrg ?? false,
  is_phone_selected: val.is_phone_selected ?? val.IsPhoneSelected ?? false,
  is_locked: val.is_locked ?? val.IsLocked ?? false,
  is_guest_account: val.is_guest_account ?? val.IsGuestAccount ?? false,
}));

export const PatientSchema = z.object({
  ID: z.string().nullish(),
  Id: z.string().nullish(),
  id: z.string().nullish(),
  PatientID: z.string().nullish(),
  PatientId: z.string().nullish(),
  patient_id: z.string().nullish(),
  PetID: z.string().nullish(),
  PetId: z.string().nullish(),
  pet_id: z.string().nullish(),
  RecordNumber: z.coerce.number().int().nullish(),
  record_number: z.coerce.number().int().nullish(),
  PetName: z.string().nullish(),
  pet_name: z.string().nullish(),
  IsNewPatient: z.boolean().nullish(),
  is_new_patient: z.boolean().nullish(),
  HasBelongings: z.boolean().nullish(),
  has_belongings: z.boolean().nullish(),
  Breed: z.string().nullish(),
  breed: z.string().nullish(),
  Species: z.string().nullish(),
  species: z.string().nullish(),
  DateOfBirth: z.string().nullish(),
  date_of_birth: z.string().nullish(),
  ProfileImageUrl: z.string().nullish(),
  profile_image_url: z.string().nullish(),
  SexName: z.string().nullish(),
  sex_name: z.string().nullish(),
  Sterilization: z.string().nullish(),
  sterilization: z.string().nullish(),
  LastWeightKgm: z.coerce.number().nullish(),
  last_weight_kgm: z.coerce.number().nullish(),
  LastWeightLb: z.coerce.number().nullish(),
  last_weight_lb: z.coerce.number().nullish(),
  Alert: z.string().nullish(),
  alert: z.string().nullish(),
  HasBitesOrScratches: z.boolean().nullish(),
  has_bites_or_scratches: z.boolean().nullish(),
}).transform(val => ({
  id: val.id || val.Id || val.ID || undefined,
  patient_id: val.patient_id || val.PatientId || val.PatientID || undefined,
  pet_id: val.pet_id || val.PetId || val.PetID || '',
  record_number: val.record_number ?? val.RecordNumber ?? undefined,
  pet_name: val.pet_name || val.PetName || undefined,
  is_new_patient: val.is_new_patient ?? val.IsNewPatient ?? false,
  has_belongings: val.has_belongings ?? val.HasBelongings ?? false,
  breed: val.breed || val.Breed || undefined,
  species: val.species || val.Species || undefined,
  date_of_birth: val.date_of_birth || val.DateOfBirth || undefined,
  profile_image_url: val.profile_image_url || val.ProfileImageUrl || undefined,
  sex_name: val.sex_name || val.SexName || undefined,
  sterilization: val.sterilization || val.Sterilization || undefined,
  last_weight_kgm: val.last_weight_kgm ?? val.LastWeightKgm ?? undefined,
  last_weight_lb: val.last_weight_lb ?? val.LastWeightLb ?? undefined,
  alert: val.alert || val.Alert || undefined,
  has_bites_or_scratches: val.has_bites_or_scratches ?? val.HasBitesOrScratches ?? false,
}));

export const AppointmentTypeSchema = z.object({
  ID: z.string().nullish(),
  Id: z.string().nullish(),
  id: z.string().nullish(),
  Name: z.string().nullish(),
  name: z.string().nullish(),
  ColorCode: z.string().nullish(),
  color_code: z.string().nullish(),
  BUAppointmentTypeId: z.string().nullish(),
  bu_appointment_type_id: z.string().nullish(),
  SubTypeId: z.string().nullish(),
  sub_type_id: z.string().nullish(),
  SubTypeName: z.string().nullish(),
  sub_type_name: z.string().nullish(),
  SubTypeDuration: z.coerce.number().int().nullish(),
  sub_type_duration: z.coerce.number().int().nullish(),
}).transform(val => ({
  id: val.id || val.Id || val.ID || '',
  name: val.name || val.Name || undefined,
  color_code: val.color_code || val.ColorCode || undefined,
  bu_appointment_type_id: val.bu_appointment_type_id || val.BUAppointmentTypeId || undefined,
  sub_type_id: val.sub_type_id || val.SubTypeId || undefined,
  sub_type_name: val.sub_type_name || val.SubTypeName || undefined,
  sub_type_duration: val.sub_type_duration ?? val.SubTypeDuration ?? undefined,
}));

export const ReasonSchema = z.object({
  ID: z.string().nullish(),
  Id: z.string().nullish(),
  id: z.string().nullish(),
  ReasonId: z.string().nullish(),
  reason_id: z.string().nullish(),
  Name: z.string().nullish(),
  name: z.string().nullish(),
}).transform(val => ({
  id: val.id || val.Id || val.ID || undefined,
  reason_id: val.reason_id || val.ReasonId || undefined,
  name: val.name || val.Name || undefined,
}));

export const StatusAuditSchema = z.object({
  TimeStamp: z.string().nullish(),
  time_stamp: z.string().nullish(),
  StatusChangedTo: z.string().nullish(),
  status_changed_to: z.string().nullish(),
  ChangedByUserId: z.string().nullish(),
  changed_by_user_id: z.string().nullish(),
  ApplicationId: z.string().nullish(),
  application_id: z.string().nullish(),
  ResourceId: z.string().nullish(),
  resource_id: z.string().nullish(),
  ResourceName: z.string().nullish(),
  resource_name: z.string().nullish(),
  AppointmentDateTime: z.string().nullish(),
  appointment_date_time: z.string().nullish(),
}).transform(val => ({
  time_stamp: val.time_stamp || val.TimeStamp || '',
  status_changed_to: val.status_changed_to || val.StatusChangedTo || undefined,
  changed_by_user_id: val.changed_by_user_id || val.ChangedByUserId || undefined,
  application_id: val.application_id || val.ApplicationId || undefined,
  resource_id: val.resource_id || val.ResourceId || undefined,
  resource_name: val.resource_name || val.ResourceName || undefined,
  appointment_date_time: val.appointment_date_time || val.AppointmentDateTime || undefined,
}));

export const AppointmentPayloadSchema = z.object({
  id: z.string(),
  OUID: z.string().nullish(),
  ouid: z.string().nullish(),
  ResourceGUID: z.string().nullish(),
  resource_guid: z.string().nullish(),
  IsEmergency: z.boolean().nullish(),
  is_emergency: z.boolean().nullish(),
  AppointmentDate: z.string().nullish(),
  appointment_date: z.string().nullish(),
  DateCreated: z.string().nullish(),
  date_created: z.string().nullish(),
  DateSTE: z.coerce.number().int().nullish(),
  date_ste: z.coerce.number().int().nullish(),
  CreatedBy: z.string().nullish(),
  created_by: z.string().nullish(),
  CreatedApplicationId: z.string().nullish(),
  created_application_id: z.string().nullish(),
  StartTime: z.string().nullish(),
  start_time: z.string().nullish(),
  StartTimeMS: z.coerce.number().int().nullish(),
  start_time_ms: z.coerce.number().int().nullish(),
  Duration: z.coerce.number().int().nullish(),
  duration: z.coerce.number().int().nullish(),
  AdmissionStatusId: z.string().nullish(),
  admission_status_id: z.string().nullish(),
  AdmissionDisplayName: z.string().nullish(),
  admission_display_name: z.string().nullish(),
  StatusId: z.coerce.number().int().nullish(),
  status_id: z.coerce.number().int().nullish(),
  Notes: z.string().nullish(),
  notes: z.string().nullish(),
  IsDeleted: z.boolean().nullish(),
  is_deleted: z.boolean().nullish(),
  ModifiedBy: z.string().nullish(),
  modified_by: z.string().nullish(),
  DateModified: z.string().nullish(),
  date_modified: z.string().nullish(),
  IsWalkin: z.boolean().nullish(),
  is_walkin: z.boolean().nullish(),
  ArrivalTs: z.string().nullish(),
  arrival_ts: z.string().nullish(),
  IsConfirmed: z.boolean().nullish(),
  is_confirmed: z.boolean().nullish(),
  IsDoctor: z.boolean().nullish(),
  is_doctor: z.boolean().nullish(),
  IsRealStaff: z.boolean().nullish(),
  is_real_staff: z.boolean().nullish(),
  PaymentDueWarning: z.boolean().nullish(),
  payment_due_warning: z.boolean().nullish(),

  Department: DepartmentSchema,
  Client: ClientSchema,
  Patient: PatientSchema,
  AppointmentType: AppointmentTypeSchema.nullish(),
  Reasons: z.array(ReasonSchema).nullish(),
  StatusAudit: z.array(StatusAuditSchema).nullish(),
}).transform(val => ({
  ouid: val.ouid || val.OUID || undefined,
  resource_guid: val.resource_guid || val.ResourceGUID || undefined,
  is_emergency: val.is_emergency ?? val.IsEmergency ?? false,
  appointment_date: val.appointment_date || val.AppointmentDate || undefined,
  date_created: val.date_created || val.DateCreated || undefined,
  date_ste: val.date_ste ?? val.DateSTE ?? undefined,
  created_by: val.created_by || val.CreatedBy || undefined,
  created_application_id: val.created_application_id || val.CreatedApplicationId || undefined,
  start_time: val.start_time || val.StartTime || undefined,
  start_time_ms: val.start_time_ms ?? val.StartTimeMS ?? undefined,
  duration: val.duration ?? val.Duration ?? undefined,
  admission_status_id: val.admission_status_id || val.AdmissionStatusId || undefined,
  admission_display_name: val.admission_display_name || val.AdmissionDisplayName || undefined,
  status_id: val.status_id ?? val.StatusId ?? undefined,
  notes: val.notes || val.Notes || undefined,
  is_deleted: val.is_deleted ?? val.IsDeleted ?? false,
  modified_by: val.modified_by || val.ModifiedBy || undefined,
  date_modified: val.date_modified || val.DateModified || undefined,
  is_walkin: val.is_walkin ?? val.IsWalkin ?? false,
  arrival_ts: val.arrival_ts || val.ArrivalTs || undefined,
  is_confirmed: val.is_confirmed ?? val.IsConfirmed ?? false,
  is_doctor: val.is_doctor ?? val.IsDoctor ?? true,
  is_real_staff: val.is_real_staff ?? val.IsRealStaff ?? true,
  payment_due_warning: val.payment_due_warning ?? val.PaymentDueWarning ?? false,
  id: val.id,

  Department: val.Department,
  Client: val.Client,
  Patient: val.Patient,
  AppointmentType: val.AppointmentType,
  Reasons: val.Reasons,
  StatusAudit: val.StatusAudit,
}));
